---

stages:
- dep
- test
- build
- deploy

.go-template:
  before_script:
  - echo "Job ${CI_JOB_NAME}"
  - ls
  image:
    name: golang:1.14-buster
    entrypoint: [""]


dep:
  extends: .go-template
  stage: dep
  artifacts:
    name: "vendor-$CI_PIPELINE_ID"
    paths:
    - .cache
    - /go/bin
    - /go/src
    expire_in: 1 hour
  script: # FIXME: change to deploy
  - make dep

test:
  extends: .go-template
  dependencies:
  - dep
  stage: test
  script:
  - make test

build:
  extends: .go-template
  dependencies:
  - dep
  stage: build
  script:
  - make build

deploy:
  extends: .go-template
  dependencies:
  - dep
  stage: deploy
  only:
    refs:
    - master
  script: 
  - make snapshot
