---

stages:
- dep
- test
- build
- deploy

.go-template:
  variables:
    GOPATH: ${CI_PROJECT_DIR}/.go
  before_script:
  - mkdir -p .go
  - echo "Job ${CI_JOB_NAME}"
  - pwd
  - ls
  cache:
    paths:
    - .go/pkg/mod/
  before_script:
  image:
    name: golang:1.14-buster
    entrypoint: [""]


dep:
  extends: .go-template
  stage: dep
  cache:
    paths:
    - .go/bin
    - .go/src
  script:
  - make dep

test:
  extends: .go-template
  dependencies:
  - dep
  stage: test
  script:
  - make test

build:
  extends: .go-template
  dependencies:
  - dep
  stage: build
  script:
  - make build

deploy:
  extends: .go-template
  dependencies:
  - dep
  stage: deploy
  only:
    refs:
    - master
  script: # FIXME: change to deploy
  - make snapshot
