// Code generated by go-swagger; DO NOT EDIT.

package developers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.com/kskewes/palace-advertising-go/models"
)

// V2AvailablePropertyImagesReader is a Reader for the V2AvailablePropertyImages structure.
type V2AvailablePropertyImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2AvailablePropertyImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV2AvailablePropertyImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewV2AvailablePropertyImagesOK creates a V2AvailablePropertyImagesOK with default headers values
func NewV2AvailablePropertyImagesOK() *V2AvailablePropertyImagesOK {
	return &V2AvailablePropertyImagesOK{}
}

/*V2AvailablePropertyImagesOK handles this case with default header values.

Images (Base64 encoded) and meta data related to 'Available Property'
*/
type V2AvailablePropertyImagesOK struct {
	Payload []*models.AvailablePropertyImages
}

func (o *V2AvailablePropertyImagesOK) Error() string {
	return fmt.Sprintf("[GET /v2AvailablePropertyImages/JSON/{PropertyCode}][%d] v2AvailablePropertyImagesOK  %+v", 200, o.Payload)
}

func (o *V2AvailablePropertyImagesOK) GetPayload() []*models.AvailablePropertyImages {
	return o.Payload
}

func (o *V2AvailablePropertyImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
