// Code generated by go-swagger; DO NOT EDIT.

package developers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/karlskewes/palace-advertising-go/models"
)

// V2AvailablePropertiesReader is a Reader for the V2AvailableProperties structure.
type V2AvailablePropertiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2AvailablePropertiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV2AvailablePropertiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewV2AvailablePropertiesOK creates a V2AvailablePropertiesOK with default headers values
func NewV2AvailablePropertiesOK() *V2AvailablePropertiesOK {
	return &V2AvailablePropertiesOK{}
}

/*V2AvailablePropertiesOK handles this case with default header values.

All 'Available Properties' with detailed data

*/
type V2AvailablePropertiesOK struct {
	Payload []*models.V2AvailablePropertyDetails
}

func (o *V2AvailablePropertiesOK) Error() string {
	return fmt.Sprintf("[GET /v2AvailableProperties/JSON][%d] v2AvailablePropertiesOK  %+v", 200, o.Payload)
}

func (o *V2AvailablePropertiesOK) GetPayload() []*models.V2AvailablePropertyDetails {
	return o.Payload
}

func (o *V2AvailablePropertiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
