// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AvailablePropertyCustomList Companies can elect to have extra field names and values that are setup specifically for their company. These can be diplayed in this 'Custom List' array with a related 'Name' and 'Value' entry. If none are setup this will return an empty array
//
// swagger:model AvailablePropertyCustomList
type AvailablePropertyCustomList struct {

	// Name of a 'Custom List Entry'
	PropertyCustomName string `json:"PropertyCustomName,omitempty"`

	// Value of a 'Custom List Entry'
	PropertyCustomValue string `json:"PropertyCustomValue,omitempty"`
}

// Validate validates this available property custom list
func (m *AvailablePropertyCustomList) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AvailablePropertyCustomList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AvailablePropertyCustomList) UnmarshalBinary(b []byte) error {
	var res AvailablePropertyCustomList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
