// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V2AvailablePropertyImages v2 available property images
//
// swagger:model v2AvailablePropertyImages
type V2AvailablePropertyImages struct {

	// Base64 encoded image.
	PropertyImageBase64 string `json:"PropertyImageBase64,omitempty"`

	// Internal 'Image Code' (This is only unique to a specific image)
	PropertyImageCode string `json:"PropertyImageCode,omitempty"`

	// Global 'Image Code' (This is unique across ALL Palace databases)
	PropertyImageCodeGlobal string `json:"PropertyImageCodeGlobal,omitempty"`

	// Free form user defined description.
	PropertyImageDescription string `json:"PropertyImageDescription,omitempty"`
}

// Validate validates this v2 available property images
func (m *V2AvailablePropertyImages) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V2AvailablePropertyImages) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V2AvailablePropertyImages) UnmarshalBinary(b []byte) error {
	var res V2AvailablePropertyImages
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
