// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V2AvailablePropertyAgentDetails v2 available property agent details
//
// swagger:model v2AvailablePropertyAgentDetails
type V2AvailablePropertyAgentDetails struct {

	// Internal 'Agent Code' referencing 'Agent'
	PropertyAgentCode string `json:"PropertyAgentCode,omitempty"`

	// 1st choice email address of 'Agent'
	PropertyAgentEmail1 string `json:"PropertyAgentEmail1,omitempty"`

	// 2nd choice email address of 'Agent'
	PropertyAgentEmail2 string `json:"PropertyAgentEmail2,omitempty"`

	// Fax No. for 'Agent'
	PropertyAgentFax string `json:"PropertyAgentFax,omitempty"`

	// Name of 'Agent'
	PropertyAgentFullName string `json:"PropertyAgentFullName,omitempty"`

	// Mobile No. for 'Agent'
	PropertyAgentPhoneMobile string `json:"PropertyAgentPhoneMobile,omitempty"`

	// Work No. for 'Agent'
	PropertyAgentPhoneWork string `json:"PropertyAgentPhoneWork,omitempty"`

	// Title for 'Agent'
	PropertyAgentTitle string `json:"PropertyAgentTitle,omitempty"`

	// External Codes provided by 3rd parties that require references to their own services
	PropertyExternalCodes string `json:"PropertyExternalCodes,omitempty"`
}

// Validate validates this v2 available property agent details
func (m *V2AvailablePropertyAgentDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V2AvailablePropertyAgentDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V2AvailablePropertyAgentDetails) UnmarshalBinary(b []byte) error {
	var res V2AvailablePropertyAgentDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
